- name: Check if job exists or not
  community.general.jenkins_job_info:
    url: http://172.31.7.18:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}"
  register: out

- name: debug
  debug:
    msg: "{{out}}"

- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.7.18:8080
    user: admin
    password: "{{jenkins_password}}"

